'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import api,{worksheetAPI} from '@/lib/api';
import PdfSurface from './PdfSurface';
const tools={fill_blank:'Text Answer',multiple_choice:'Multiple Choice',true_false:'True / False',matching:'Matching',essay:'Teacher Review'};
export default function PdfEditor({id}){
 const [ws,setWs]=useState(null),[url,setUrl]=useState(''),[fields,setFields]=useState([]),[selected,setSelected]=useState(null),[tool,setTool]=useState('select'),[page,setPage]=useState(1),[pages,setPages]=useState(1),[error,setError]=useState(''),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false),[revision,setRevision]=useState(0),[feedbackMode,setFeedbackMode]=useState('score'),[attempts,setAttempts]=useState(1),[dirty,setDirty]=useState(false);
 const surface=useRef(null),gesture=useRef(null),field=fields.find(f=>f.id===selected);
 useEffect(()=>{let active=true;Promise.all([worksheetAPI.getOne(id),worksheetAPI.getFile(id)]).then(([wr,fr])=>{if(!active)return;const w=wr.data.data.worksheet,f=fr.data.data;if(f.mimeType!=='application/pdf')throw Error('Make Interactive requires a PDF.');setWs(w);setUrl(f.fileUrl||f.dataUrl);setRevision(w.layoutRevision||0);setFeedbackMode(w.feedbackMode||'score');setAttempts(w.maxAttempts??0);setFields((w.interactiveLayout?.fields||[]).map(box=>({...w.questions.find(q=>q.id===box.id),...box})));}).catch(e=>active&&setError(e.response?.data?.message||e.message)).finally(()=>{});return()=>{active=false;};},[id]);
 useEffect(()=>{const warn=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const change=(patch)=>{setFields(all=>all.map(f=>f.id===selected?{...f,...patch}:f));setDirty(true);setNotice('');};
 const point=e=>{const r=surface.current.getBoundingClientRect();return {x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};};
 function begin(e,f,resize=false){if(e.button!==0)return;e.preventDefault();e.stopPropagation();surface.current.setPointerCapture(e.pointerId);const p=point(e);
  if(f){setSelected(f.id);gesture.current={kind:resize?'resize':'move',start:p,original:{...f},id:f.id};}
  else if(tool!=='select'){const id=crypto.randomUUID(),newField={id,page,type:tool,text:`Field ${fields.length+1}`,x:Math.min(p.x,.94),y:Math.min(p.y,.94),width:.06,height:.04,points:1,acceptedAnswers:[],options:['Option A','Option B'],correctAnswer:tool==='true_false'?'true':'Option A',pairs:[{left:'One',right:'Uno'},{left:'Two',right:'Dos'}],teacherReview:tool==='essay',sampleAnswer:''};setFields(all=>[...all,newField]);setSelected(id);gesture.current={kind:'draw',start:{x:newField.x,y:newField.y},original:newField,id};setDirty(true);}
  else setSelected(null);
 }
 function move(e){const g=gesture.current;if(!g)return;const p=point(e),dx=p.x-g.start.x,dy=p.y-g.start.y;setFields(all=>all.map(f=>{if(f.id!==g.id)return f;const o=g.original;if(g.kind==='move')return {...f,x:Math.max(0,Math.min(1-o.width,o.x+dx)),y:Math.max(0,Math.min(1-o.height,o.y+dy))};return {...f,width:Math.max(.025,Math.min(1-o.x,g.kind==='draw'?dx:o.width+dx)),height:Math.max(.02,Math.min(1-o.y,g.kind==='draw'?dy:o.height+dy))};}));setDirty(true);setNotice('');}
 function end(){if(gesture.current?.kind==='draw')setTool('select');gesture.current=null;}
 async function save(){setSaving(true);setError('');setNotice('');try{const r=await api.put(`/worksheets/${id}/interactive`,{revision,pageCount:pages,fields,feedbackMode,maxAttempts:Number(attempts)});setWs(r.data.data.worksheet);setRevision(r.data.data.worksheet.layoutRevision);setDirty(false);setNotice('Interactive fields saved. You can now publish and assign this worksheet.');}catch(e){setError(e.response?.data?.message||'Could not save. Your fields remain in this editor.');}finally{setSaving(false);}}
 return <main className="max-w-[1440px] mx-auto px-4 py-6 space-y-5"><Link href={`/worksheets/${id}`} className="btn btn-ghost">← Back to worksheet</Link><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Make Interactive</h1><p className="text-neutral-600">{ws?.title} · Select a tool and draw a box on the PDF.</p></div><button onClick={save} disabled={saving||!ws||!fields.length} className="btn btn-primary">{saving?'Saving…':'Save interactive worksheet'}</button></div>{error&&<p role="alert" className="p-3 rounded-xl bg-red-50 text-red-700">{error}</p>}{notice&&<p role="status" className="p-3 rounded-xl bg-green-50 text-green-800">{notice}</p>}
 <div className="flex flex-wrap gap-2"><button className={`btn ${tool==='select'?'btn-primary':'btn-outline'}`} onClick={()=>setTool('select')}>Select / move</button>{Object.entries(tools).map(([key,label])=><button className={`btn ${tool===key?'btn-primary':'btn-outline'}`} key={key} onClick={()=>setTool(key)}>+ {label}</button>)}</div>
 <div className="grid lg:grid-cols-[minmax(0,1fr)_320px] gap-6 items-start"><section className="min-w-0 space-y-3"><div className="flex justify-between items-center"><button disabled={page<=1} className="btn btn-outline" onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} / {pages}</span><button disabled={page>=pages} className="btn btn-outline" onClick={()=>setPage(p=>p+1)}>Next</button></div>{url&&<PdfSurface url={url} page={page} onPages={setPages}><div ref={surface} className="absolute inset-0" style={{touchAction:'none',cursor:tool==='select'?'default':'crosshair'}} onPointerDown={e=>begin(e)} onPointerMove={move} onPointerUp={end} onPointerCancel={end}>{fields.filter(f=>f.page===page).map(f=><div role="button" tabIndex={0} aria-label={`Field: ${f.text}`} data-testid="editor-field" key={f.id} onPointerDown={e=>begin(e,f)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();setSelected(f.id);const dx=e.key==='ArrowLeft'?-.005:e.key==='ArrowRight'?.005:0,dy=e.key==='ArrowUp'?-.005:e.key==='ArrowDown'?.005:0;setFields(all=>all.map(v=>v.id===f.id?{...v,x:Math.max(0,Math.min(1-v.width,v.x+dx)),y:Math.max(0,Math.min(1-v.height,v.y+dy))}:v));setDirty(true);}}} style={{position:'absolute',left:`${f.x*100}%`,top:`${f.y*100}%`,width:`${f.width*100}%`,height:`${f.height*100}%`,border:`2px solid ${f.id===selected?'#7c3aed':'#0284c7'}`,background:f.id===selected?'#ede9febf':'#e0f2febf',cursor:'move'}}><span className="block truncate text-xs text-slate-900 px-1">{f.text} · {f.points} pt</span><button aria-label="Resize field" className="absolute bottom-0 right-0 bg-violet-600 w-4 h-4 cursor-se-resize" onPointerDown={e=>begin(e,f,true)}/></div>)}</div></PdfSurface>}<p className="text-sm text-neutral-500">Drag a field to move it. Drag its lower-right corner to resize. Arrow keys move the focused field.</p></section>
 <aside className="space-y-4 lg:sticky lg:top-4"><section className="card space-y-3"><h2 className="font-bold">Activity settings</h2><label className="block text-sm">Attempts (0 = unlimited)<input className="input" type="number" min="0" max="100" value={attempts} onChange={e=>{setAttempts(e.target.value);setDirty(true);}}/></label><label className="block text-sm">Student feedback<select className="input" value={feedbackMode} onChange={e=>{setFeedbackMode(e.target.value);setDirty(true);}}><option value="score">Score only</option><option value="incorrect">Score + incorrect questions</option><option value="answers">Score + correct answers</option><option value="full">Full feedback</option><option value="after_review">Full feedback after teacher review</option></select></label><p className="text-xs text-neutral-500">Mixed activities show the final score after all manual questions are reviewed. Saving changes requires students with an open draft to restart that version.</p></section>
 {field?<section className="card space-y-3"><h2 className="font-bold">{tools[field.type]||field.type}</h2><label className="block text-sm">Field label<input className="input" value={field.text} onChange={e=>change({text:e.target.value})}/></label><label className="block text-sm">Points<input className="input" type="number" min="1" max="100" value={field.points} onChange={e=>change({points:Number(e.target.value)})}/></label>
 {['fill_blank','short_answer'].includes(field.type)&&<><label className="block text-sm">Accepted answers (one per line)<textarea className="input" rows={4} value={(field.acceptedAnswers||[]).join('\n')} onChange={e=>change({acceptedAnswers:e.target.value.split('\n')})}/></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={!!field.caseSensitive} onChange={e=>change({caseSensitive:e.target.checked})}/>Case sensitive</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={!!field.teacherReview} onChange={e=>change({teacherReview:e.target.checked})}/>Teacher Review</label></>}
 {field.type==='multiple_choice'&&<><label className="block text-sm">Options (one per line)<textarea className="input" value={(field.options||[]).join('\n')} onChange={e=>change({options:e.target.value.split('\n')})}/></label><label className="block text-sm">Correct answer<select className="input" value={field.correctAnswer||''} onChange={e=>change({correctAnswer:e.target.value})}><option value="">Choose…</option>{field.options?.map((o,i)=><option key={i} value={o}>{o}</option>)}</select></label></>}
 {field.type==='true_false'&&<label className="block text-sm">Correct answer<select className="input" value={String(field.correctAnswer)} onChange={e=>change({correctAnswer:e.target.value})}><option value="true">True</option><option value="false">False</option></select></label>}
 {field.type==='matching'&&<div className="space-y-2"><p className="text-sm">Matching pairs</p>{field.pairs?.map((pair,i)=><div className="flex gap-1" key={i}>{['left','right'].map(side=><input key={side} aria-label={`${side} item ${i+1}`} className="input min-w-0 w-1/2" value={pair[side]} onChange={e=>change({pairs:field.pairs.map((p,n)=>n===i?{...p,[side]:e.target.value}:p)})}/>)}<button aria-label={`Remove pair ${i+1}`} onClick={()=>change({pairs:field.pairs.filter((_,n)=>n!==i)})}>×</button></div>)}<button className="btn btn-outline" onClick={()=>change({pairs:[...field.pairs,{left:'',right:''}]})}>Add pair</button></div>}
 {(field.type==='essay'||field.teacherReview)&&<label className="block text-sm">Model answer (teacher only)<textarea className="input" value={field.sampleAnswer||''} onChange={e=>change({sampleAnswer:e.target.value})}/></label>}
 <button className="btn btn-ghost text-red-600" onClick={()=>{setFields(all=>all.filter(f=>f.id!==selected));setSelected(null);setDirty(true);}}>Delete field</button></section>:<section className="card text-neutral-500 text-sm">Select a field to edit its answer and points.</section>}
 <section className="card"><h2 className="font-bold mb-2">Fields · {fields.length}</h2>{fields.map((f,i)=><button key={f.id} className="block w-full text-left text-sm py-2 border-b" onClick={()=>{setSelected(f.id);setPage(f.page);}}>{i+1}. {f.text} · page {f.page}</button>)}</section></aside></div></main>;
}
