'use client';
import {useEffect,useRef,useState} from 'react';
import api,{submissionAPI} from '@/lib/api';
import PdfSurface from './PdfSurface';
import SubmissionFeedback from './SubmissionFeedback';
export default function PdfPlayer({worksheet,url,student}){
 const [page,setPage]=useState(1),[pages,setPages]=useState(worksheet.interactiveLayout.pageCount),[answers,setAnswers]=useState({}),[attempt,setAttempt]=useState(null),[result,setResult]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[history,setHistory]=useState([]),[zoom,setZoom]=useState(100),[resetNeeded,setResetNeeded]=useState(false);
 const locked=useRef(false),startLock=useRef(false),answersRef=useRef({});
 const questions=worksheet.questions||[];
 useEffect(()=>{answersRef.current=answers;},[answers]);
 useEffect(()=>{if(student)loadHistory();},[worksheet.id,student]);
 async function loadHistory(){try{const me=await api.get('/auth/me');const r=await submissionAPI.getByStudent(me.data.data.user.id,{worksheetId:worksheet.id});setHistory((r.data.data.submissions||[]).filter(s=>s.worksheetId===worksheet.id));}catch{setError('Could not load previous attempts. You can retry below.');}}
 async function start(reset=false){if(startLock.current)return;startLock.current=true;setBusy(true);setError('');try{const r=await api.post(`/worksheets/${worksheet.id}/attempt`,{reset,revision:worksheet.layoutRevision});const d=r.data.data;setAttempt(d);setAnswers(Object.fromEntries(d.draft.answers.map(a=>[a.questionId,a.answer])));setResult(null);setResetNeeded(false);setNotice(d.draft.answers.length?'Saved draft restored.':'Attempt started. Save your answers before leaving.');}catch(e){setError(e.response?.data?.message||'Could not start.');setResetNeeded(e.response?.status===409&&/updated|version/i.test(e.response?.data?.message||''));}finally{startLock.current=false;setBusy(false);}}
 const payload=()=>({attemptToken:attempt.draft.attemptToken,answers:questions.map(q=>({questionId:q.id,answer:answersRef.current[q.id]??null}))});
 async function save(){if(locked.current||!attempt)return;locked.current=true;setBusy(true);setError('');try{await api.put(`/worksheets/${worksheet.id}/draft`,payload());setNotice('Answers saved. You can return to this attempt later.');}catch(e){setError(e.response?.data?.message||'Could not save. Keep this page open and retry.');}finally{locked.current=false;setBusy(false);}}
 async function submit(){if(locked.current||!attempt)return;const unanswered=questions.some(q=>{const a=answersRef.current[q.id];return a==null||a===''||(q.type==='matching'&&(q.pairs||[]).some(p=>!a[p.left]));});if(unanswered&&!confirm('Some fields are empty. Submit anyway?'))return;
  locked.current=true;setBusy(true);setError('');try{const r=await submissionAPI.submit({worksheetId:worksheet.id,...payload()});setResult(r.data.data.submission);setAttempt(null);setNotice('Submission received.');await loadHistory();}catch(e){setError(e.response?.data?.message||'Submission could not be confirmed. Retry: the same attempt will not be counted twice.');}finally{locked.current=false;setBusy(false);}
 }
 function change(id,value){setAnswers(a=>({...a,[id]:value}));setNotice('Unsaved changes. Use Save answers before leaving.');}
 return <section className="space-y-4"><div className="card space-y-3"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-xl font-bold">Interactive PDF</h2>{student&&!attempt&&<button className="btn btn-primary" disabled={busy} onClick={()=>start()}>{history.length?'Start / resume next attempt':'Start / resume activity'}</button>}</div><p className="text-sm text-neutral-600">{student?'Answer directly on the PDF. Use zoom for small fields.':'Teacher preview. Student answers are entered on the original PDF.'} · {worksheet.maxAttempts||'Unlimited'} attempts</p>{attempt&&<p>Attempt {attempt.attemptNumber} · Started {new Date(attempt.draft.startedAt).toLocaleTimeString()}</p>}{error&&<p role="alert" className="text-red-700">{error} <button className="underline" onClick={()=>window.location.reload()}>Reload worksheet</button></p>}{resetNeeded&&<button className="btn btn-outline" onClick={()=>{if(confirm('Discard the saved draft from the previous version?'))start(true);}}>Discard old draft and restart</button>}{notice&&<p role="status" className="text-primary-700">{notice}</p>}</div>
 <div className="flex flex-wrap justify-between items-center gap-3"><button className="btn btn-outline" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous page</button><span>Page {page} / {pages}</span><button className="btn btn-outline" disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>Next page</button><label className="text-sm">Zoom <select className="input" value={zoom} onChange={e=>setZoom(Number(e.target.value))}>{[100,125,150,200].map(n=><option key={n} value={n}>{n}%</option>)}</select></label></div>
 <div className="overflow-x-auto pb-3"><div style={{width:`${zoom}%`,minWidth:360}}><PdfSurface url={url} page={page} onPages={setPages}>{worksheet.interactiveLayout.fields.filter(f=>f.page===page).map(box=>{const q=questions.find(q=>q.id===box.id);if(!q)return null;return <div data-testid="answer-field" key={box.id} style={{position:'absolute',left:`${box.x*100}%`,top:`${box.y*100}%`,width:`${box.width*100}%`,height:`${box.height*100}%`}}><OverlayInput q={q} value={answers[q.id]} onChange={v=>change(q.id,v)} disabled={!student||!attempt||busy}/></div>;})}</PdfSurface></div></div>
 {student&&attempt&&<div className="flex flex-wrap justify-end gap-3"><button className="btn btn-outline" onClick={save} disabled={busy}>Save answers</button><button className="btn btn-primary" onClick={submit} disabled={busy}>{busy?'Saving…':'Submit worksheet'}</button></div>}
 {result&&<SubmissionFeedback submission={result}/>}
 {student&&<details className="card" open><summary className="font-bold cursor-pointer">Attempt history ({history.length})</summary><button className="btn btn-ghost" onClick={loadHistory}>Refresh results</button>{history.map(s=><SubmissionFeedback key={s.id} submission={s}/>)}</details>}
 </section>;
}
function OverlayInput({q,value,onChange,disabled}){
 const cls='w-full h-full min-h-0 rounded border-2 border-primary-500 bg-white/95 text-neutral-900 px-1 focus:outline-none focus:ring-2 focus:ring-primary-400 disabled:bg-neutral-100/90';
 if(['multiple_choice','true_false'].includes(q.type))return <select aria-label={q.text} className={cls} value={value??''} onChange={e=>onChange(q.answerFormat==='index'?Number(e.target.value):e.target.value)} disabled={disabled}><option value="">Choose…</option>{(q.type==='true_false'?['true','false']:q.options||[]).map((v,i)=><option key={i} value={q.answerFormat==='index'?i:v}>{v}</option>)}</select>;
 if(q.type==='matching')return <div className={`${cls} overflow-auto p-1`}>{(q.pairs||[]).map((p,i)=><label key={i} className="grid grid-cols-2 items-center gap-1 text-xs mb-1"><span>{p.left}</span><select aria-label={`${q.text}: ${p.left}`} className="min-w-0 border rounded p-1" value={value?.[p.left]||''} disabled={disabled} onChange={e=>onChange({...value,[p.left]:e.target.value})}><option value="">Choose…</option>{(q.matchingOptions||q.pairs.map(p=>p.right).sort()).map((v,n)=><option key={n}>{v}</option>)}</select></label>)}</div>;
 if(q.type==='essay')return <textarea aria-label={q.text} className={cls} value={value||''} disabled={disabled} onChange={e=>onChange(e.target.value)}/>;
 return <input aria-label={q.text} autoComplete="off" className={cls} value={value||''} disabled={disabled} onChange={e=>onChange(e.target.value)}/>;
}
