'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {submissionAPI} from '@/lib/api';
export default function TeacherReview({id}){
 const [submissions,setSubmissions]=useState([]),[selected,setSelected]=useState(null),[reviews,setReviews]=useState({}),[feedback,setFeedback]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('all'),[legacyScore,setLegacyScore]=useState('');
 async function load(){try{const r=await submissionAPI.getByWorksheet(id);setSubmissions(r.data.data.submissions||[]);}catch(e){setError(e.response?.data?.message||'Could not load submissions.');}}
 useEffect(()=>{load();},[id]);
 function choose(s){setSelected(s);setReviews(Object.fromEntries((s.answers||[]).map(a=>[a.questionId,{points:a.requiresManualReview?'':a.pointsEarned??'',comment:a.comment||''}])));setFeedback(s.feedback||'');setLegacyScore(s.score??'');setError('');setNotice('');}
 async function save(e){e.preventDefault();setBusy(true);setError('');try{
  const data=selected.gradingSnapshot?{reviews:Object.entries(reviews).filter(([,v])=>v.points!=='').map(([questionId,v])=>({questionId,points:Number(v.points),comment:v.comment})),feedback}:{score:Number(legacyScore),feedback};
  const r=await submissionAPI.grade(selected.id,data);choose({...r.data.data.submission,student:selected.student});setNotice('Review saved. Final scores update when all pending questions are reviewed.');await load();
 }catch(e){setError(e.response?.data?.message||'Could not save review.');}finally{setBusy(false);}}
 const shown=submissions.filter(s=>filter==='all'||(s.gradingSnapshot?.feedbackMode==='after_review'&&s.status!=='reviewed')||s.answers?.some(a=>a.requiresManualReview)||['pending','submitted'].includes(s.status)&&s.maxScore>0);
 return <main className="max-w-7xl mx-auto p-6 space-y-5"><Link href={`/worksheets/${id}`} className="btn btn-ghost">← Back to worksheet</Link><h1 className="text-3xl font-bold">Teacher Review</h1>{error&&<p role="alert" className="text-red-700">{error}</p>}{notice&&<p role="status" className="text-green-700">{notice}</p>}<div className="grid md:grid-cols-[280px_minmax(0,1fr)] gap-6"><aside className="card space-y-3"><select aria-label="Submission filter" className="input" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All submissions</option><option value="pending">Needs review</option></select><button className="btn btn-outline" onClick={load}>Refresh</button>{!shown.length&&<p>No submissions in this view.</p>}{shown.map(s=><button key={s.id} onClick={()=>choose(s)} className={`block text-left w-full p-3 rounded-xl border ${selected?.id===s.id?'border-primary-500 bg-primary-50':''}`}><strong>{s.student?.firstName} {s.student?.lastName}</strong><p className="text-sm">Attempt {s.attemptNumber} · {s.status}</p><p className="text-xs">{new Date(s.submittedAt).toLocaleString()}</p></button>)}</aside>
 <section>{selected?<form onSubmit={save} className="space-y-4"><div className="card"><h2 className="font-bold text-xl">{selected.student?.firstName} {selected.student?.lastName}</h2><p>Attempt {selected.attemptNumber} · Auto score: {selected.autoScore??'—'} / {selected.maxScore??'—'}</p><p>Current total: {selected.score??'—'} · Pending questions: {selected.answers?.filter(a=>a.requiresManualReview).length||0}</p></div>{selected.gradingSnapshot?(selected.gradingSnapshot.questions||[]).map((q,i)=>{const a=selected.answers?.find(a=>a.questionId===q.id),v=reviews[q.id]||{points:'',comment:''};return <article key={q.id} className="card space-y-3"><h3 className="font-bold">{i+1}. {q.text||q.question}</h3><p className="whitespace-pre-wrap">Student answer: {typeof a?.answer==='string'?a.answer:JSON.stringify(a?.answer??null)}</p>{q.sampleAnswer&&<p className="text-neutral-600">Model answer: {q.sampleAnswer}</p>}<p className="text-sm">{a?.requiresManualReview?'Pending review':'Scored'} · Maximum {q.points} points</p><label className="block text-sm">Points awarded<input type="number" min="0" max={q.points} step="0.01" className="input" value={v.points} onChange={e=>setReviews({...reviews,[q.id]:{...v,points:e.target.value}})}/></label><label className="block text-sm">Teacher comment<textarea className="input" value={v.comment} onChange={e=>setReviews({...reviews,[q.id]:{...v,comment:e.target.value}})}/></label></article>;}):<div className="card"><p>This is a legacy or resource submission. Its original answers are preserved.</p><pre className="whitespace-pre-wrap text-sm">{JSON.stringify(selected.answers,null,2)}</pre><label>Score / {selected.maxScore??100}<input className="input" required type="number" min="0" max={selected.maxScore??100} value={legacyScore} onChange={e=>setLegacyScore(e.target.value)}/></label></div>}
 <section className="card space-y-3"><label className="block">Overall feedback<textarea className="input" value={feedback} onChange={e=>setFeedback(e.target.value)}/></label><button className="btn btn-primary" disabled={busy}>{busy?'Saving…':'Save Review'}</button></section></form>:<div className="card text-neutral-500">Select a submission to review.</div>}</section></div></main>;
}
