'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import api from '@/lib/api';
const fmt=n=>n==null?'—':`${n}%`,time=n=>n==null?'—':`${Math.round(n/60)} min`;
function Filter({type,label,value,onChange}){const [search,setSearch]=useState(''),[options,setOptions]=useState([]),[error,setError]=useState('');useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>{api.get('/analytics/options',{params:{type,search},signal:controller.signal}).then(r=>{setOptions(r.data.data.options);setError('');}).catch(e=>{if(e.code!=='ERR_CANCELED')setError('Filter unavailable');});},250);return()=>{clearTimeout(timer);controller.abort();};},[type,search]);return <div><label className="text-sm font-medium">{label}<input aria-label={`Search ${label}`} className="input mt-1" placeholder={`Search ${label.toLowerCase()}…`} value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label={label} className="input mt-1" value={value} onChange={e=>onChange(e.target.value)}><option value="">All {label.toLowerCase()}</option>{value&&!options.some(o=>o.id===value)&&<option value={value}>Selected filter</option>}{options.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>{error&&<p className="text-xs text-red-700">{error}</p>}</div>;}
export default function AnalyticsPanel(){const [filters,setFilters]=useState({groupId:'',studentId:'',worksheetId:'',from:'',to:''}),[view,setView]=useState('students'),[page,setPage]=useState(1),[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');api.get('/analytics',{params:{...filters,view,page},signal:controller.signal}).then(r=>setData(r.data.data)).catch(e=>{if(e.code!=='ERR_CANCELED')setError(e.response?.data?.message||'Could not load analytics.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[filters,view,page,refresh]);
 const filter=(key,value)=>{setFilters(f=>({...f,[key]:value}));setPage(1);},summary=data?.summary;
 return <section className="space-y-6"><div className="flex justify-between gap-4 items-center"><h2 className="text-2xl font-bold">Learning Analytics</h2><button className="btn btn-outline" onClick={()=>setRefresh(n=>n+1)}>Refresh</button></div><div className="card grid sm:grid-cols-2 lg:grid-cols-5 gap-4"><Filter type="groups" label="Groups" value={filters.groupId} onChange={v=>filter('groupId',v)}/><Filter type="students" label="Students" value={filters.studentId} onChange={v=>filter('studentId',v)}/><Filter type="worksheets" label="Worksheets" value={filters.worksheetId} onChange={v=>filter('worksheetId',v)}/><label className="text-sm">Submitted from (UTC)<input className="input mt-1" type="date" value={filters.from} onChange={e=>filter('from',e.target.value)}/></label><label className="text-sm">Submitted through (UTC)<input className="input mt-1" type="date" value={filters.to} onChange={e=>filter('to',e.target.value)}/></label><button className="btn btn-ghost" onClick={()=>{setFilters({groupId:'',studentId:'',worksheetId:'',from:'',to:''});setPage(1);}}>Clear filters</button></div>
 {error&&<p role="alert" className="bg-red-50 text-red-700 p-4 rounded-xl">{error}</p>}{loading&&<p role="status">Loading results…</p>}{summary&&!error&&<div className={`grid grid-cols-2 lg:grid-cols-4 gap-4 ${loading?'opacity-50':''}`}>{[['Average Score',fmt(summary.averageScore)],['Completed',`${summary.completed} / ${summary.assigned}`],['To Review',summary.toReview],['Average Time',time(summary.averageTimeSeconds)]].map(([label,value])=><div key={label} className="card"><p className="text-sm text-neutral-500">{label}</p><strong className="text-3xl">{value}</strong></div>)}</div>}
 <p className="text-sm text-neutral-600">Rule: latest attempt for each student and worksheet within the selected submission dates. Final grades only in score averages. Completion uses the current assigned roster, deduplicated across groups. Needs Attention: average below 70% or at least 3 incomplete assignments. Filters search up to 50 matching records.</p>
 <div className="flex flex-wrap gap-2">{[['students','By student'],['groups','By group'],['worksheets','By worksheet'],['questions','Most difficult questions']].map(([key,label])=><button key={key} className={`btn ${view===key?'btn-primary':'btn-outline'}`} onClick={()=>{setView(key);setPage(1);}}>{label}</button>)}</div>
 {data&&!error&&<div className="card overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr>{(view==='questions'?['Question','Worksheet','Evaluated','Incorrect','Error rate']:['Name','Completed','Average','Attempts','Avg. time','Last activity','Action']).map(t=><th key={t} className="p-3 border-b whitespace-nowrap">{t}</th>)}</tr></thead><tbody>{data.rows.map(row=><tr key={view==='questions'?`${row.worksheetId}-${row.id}`:row.id}>{view==='questions'?<><td className="p-3 border-b">{row.name}</td><td className="p-3 border-b"><Link className="text-primary-700 underline" href={`/worksheets/${row.worksheetId}`}>{row.worksheetTitle}</Link></td><td className="p-3 border-b">{row.evaluated}</td><td className="p-3 border-b">{row.incorrect}</td><td className="p-3 border-b font-semibold">{fmt(row.incorrectPercent)}</td></>:<><td className="p-3 border-b"><strong>{row.name}</strong>{row.needsAttention&&<p className="text-amber-700 text-xs">Needs Attention</p>}</td><td className="p-3 border-b">{row.completed} / {row.assigned}</td><td className="p-3 border-b">{fmt(row.averageScore)}</td><td className="p-3 border-b">{view==='students'?row.attempts:row.averageAttempts??'—'}{view!=='students'?' avg.':''}</td><td className="p-3 border-b">{time(row.averageTimeSeconds)}</td><td className="p-3 border-b">{row.lastActivity?new Date(row.lastActivity).toLocaleDateString():'—'}</td><td className="p-3 border-b">{view==='worksheets'?<Link className="text-primary-700 underline" href={`/worksheets/${row.id}/review`}>Review</Link>:<button className="text-primary-700 underline" onClick={()=>{filter(view==='groups'?'groupId':'studentId',row.id);setView(view==='groups'?'students':'worksheets');}}>Details</button>}</td></>}</tr>)}</tbody></table>{!data.rows.length&&<p className="py-8 text-neutral-500">No results for these filters.</p>}<div className="flex justify-between gap-4 mt-4"><button className="btn btn-outline" disabled={page<=1||loading} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} / {data.pages} · {data.total} rows</span><button className="btn btn-outline" disabled={page>=data.pages||loading} onClick={()=>setPage(p=>p+1)}>Next</button></div></div>}
 </section>;
}
